blank_issues_enabled: false
contact_links:
  - name: 🌐 Eatensity Website
    url: https://eatensity.com
    about: Visit the Eatensity web app
  - name: 📖 Help & FAQs
    url: https://eatensity.com/about
    about: Learn more about Eatensity and how to use it
